USE adopciones;
DROP TABLE adopciones;
DROP TABLE busquedas;
DROP TABLE mascotas;
DROP TABLE detalles;
DROP TABLE dueños;
DROP TABLE refugios;
DROP TABLE usuario_roles;
DROP TABLE usuarios;
DROP TABLE roles;
