USE ADOPCIONES;

#Roles
INSERT INTO ROLES (rol_nombre) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (rol_nombre) VALUES ('ROLE_USER');

#Especies
INSERT INTO ESPECIES (nombre) VALUES ('PERRO');
INSERT INTO ESPECIES (nombre) VALUES ('GATO');
INSERT INTO ESPECIES (nombre) VALUES ('HAMSTERS');
INSERT INTO ESPECIES (nombre) VALUES ('TORTUGAS');
INSERT INTO ESPECIES (nombre) VALUES ('PALOMAS');

COMMIT;